package bo.edu.uto.dea.jhs.persistence;
// Generated 14-abr-2014 4:37:45 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Carrera generated by hbm2java
 */
public class Carrera  implements java.io.Serializable {


     private long idCarrera;
     private Facultad facultad;
     private String siglaCarrera;
     private String nombre;
     private String estado;
     private Set materias = new HashSet(0);
     private Set directorCarreras = new HashSet(0);
     private Set comisionEvaluadoras = new HashSet(0);
     private Set docenteEscalafons = new HashSet(0);

    public Carrera() {
    }

	
    public Carrera(long idCarrera, Facultad facultad, String siglaCarrera) {
        this.idCarrera = idCarrera;
        this.facultad = facultad;
        this.siglaCarrera = siglaCarrera;
    }
    public Carrera(long idCarrera, Facultad facultad, String siglaCarrera, String nombre, String estado, Set materias, Set directorCarreras, Set comisionEvaluadoras, Set docenteEscalafons) {
       this.idCarrera = idCarrera;
       this.facultad = facultad;
       this.siglaCarrera = siglaCarrera;
       this.nombre = nombre;
       this.estado = estado;
       this.materias = materias;
       this.directorCarreras = directorCarreras;
       this.comisionEvaluadoras = comisionEvaluadoras;
       this.docenteEscalafons = docenteEscalafons;
    }
   
    public long getIdCarrera() {
        return this.idCarrera;
    }
    
    public void setIdCarrera(long idCarrera) {
        this.idCarrera = idCarrera;
    }
    public Facultad getFacultad() {
        return this.facultad;
    }
    
    public void setFacultad(Facultad facultad) {
        this.facultad = facultad;
    }
    public String getSiglaCarrera() {
        return this.siglaCarrera;
    }
    
    public void setSiglaCarrera(String siglaCarrera) {
        this.siglaCarrera = siglaCarrera;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getMaterias() {
        return this.materias;
    }
    
    public void setMaterias(Set materias) {
        this.materias = materias;
    }
    public Set getDirectorCarreras() {
        return this.directorCarreras;
    }
    
    public void setDirectorCarreras(Set directorCarreras) {
        this.directorCarreras = directorCarreras;
    }
    public Set getComisionEvaluadoras() {
        return this.comisionEvaluadoras;
    }
    
    public void setComisionEvaluadoras(Set comisionEvaluadoras) {
        this.comisionEvaluadoras = comisionEvaluadoras;
    }
    public Set getDocenteEscalafons() {
        return this.docenteEscalafons;
    }
    
    public void setDocenteEscalafons(Set docenteEscalafons) {
        this.docenteEscalafons = docenteEscalafons;
    }




}


