package bo.edu.uto.dea.jhs.persistence;
// Generated 14-abr-2014 4:37:45 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Cartilla generated by hbm2java
 */
public class Cartilla  implements java.io.Serializable {


     private long idCartilla;
     private DocenteEscalafon docenteEscalafon;
     private double totalHoras;
     private double totalParcial;
     private double notaPromedio;
     private double puntajeEscalafon;
     private String gestion;
     private Set evaluacionEscalafons = new HashSet(0);
     private Set escalafons = new HashSet(0);
     private Set contenidoCartillas = new HashSet(0);
     private Set resolucions = new HashSet(0);

    public Cartilla() {
    }

	
    public Cartilla(long idCartilla, DocenteEscalafon docenteEscalafon, double totalHoras, double totalParcial, double notaPromedio, double puntajeEscalafon, String gestion) {
        this.idCartilla = idCartilla;
        this.docenteEscalafon = docenteEscalafon;
        this.totalHoras = totalHoras;
        this.totalParcial = totalParcial;
        this.notaPromedio = notaPromedio;
        this.puntajeEscalafon = puntajeEscalafon;
        this.gestion = gestion;
    }
    public Cartilla(long idCartilla, DocenteEscalafon docenteEscalafon, double totalHoras, double totalParcial, double notaPromedio, double puntajeEscalafon, String gestion, Set evaluacionEscalafons, Set escalafons, Set contenidoCartillas, Set resolucions) {
       this.idCartilla = idCartilla;
       this.docenteEscalafon = docenteEscalafon;
       this.totalHoras = totalHoras;
       this.totalParcial = totalParcial;
       this.notaPromedio = notaPromedio;
       this.puntajeEscalafon = puntajeEscalafon;
       this.gestion = gestion;
       this.evaluacionEscalafons = evaluacionEscalafons;
       this.escalafons = escalafons;
       this.contenidoCartillas = contenidoCartillas;
       this.resolucions = resolucions;
    }
   
    public long getIdCartilla() {
        return this.idCartilla;
    }
    
    public void setIdCartilla(long idCartilla) {
        this.idCartilla = idCartilla;
    }
    public DocenteEscalafon getDocenteEscalafon() {
        return this.docenteEscalafon;
    }
    
    public void setDocenteEscalafon(DocenteEscalafon docenteEscalafon) {
        this.docenteEscalafon = docenteEscalafon;
    }
    public double getTotalHoras() {
        return this.totalHoras;
    }
    
    public void setTotalHoras(double totalHoras) {
        this.totalHoras = totalHoras;
    }
    public double getTotalParcial() {
        return this.totalParcial;
    }
    
    public void setTotalParcial(double totalParcial) {
        this.totalParcial = totalParcial;
    }
    public double getNotaPromedio() {
        return this.notaPromedio;
    }
    
    public void setNotaPromedio(double notaPromedio) {
        this.notaPromedio = notaPromedio;
    }
    public double getPuntajeEscalafon() {
        return this.puntajeEscalafon;
    }
    
    public void setPuntajeEscalafon(double puntajeEscalafon) {
        this.puntajeEscalafon = puntajeEscalafon;
    }
    public String getGestion() {
        return this.gestion;
    }
    
    public void setGestion(String gestion) {
        this.gestion = gestion;
    }
    public Set getEvaluacionEscalafons() {
        return this.evaluacionEscalafons;
    }
    
    public void setEvaluacionEscalafons(Set evaluacionEscalafons) {
        this.evaluacionEscalafons = evaluacionEscalafons;
    }
    public Set getEscalafons() {
        return this.escalafons;
    }
    
    public void setEscalafons(Set escalafons) {
        this.escalafons = escalafons;
    }
    public Set getContenidoCartillas() {
        return this.contenidoCartillas;
    }
    
    public void setContenidoCartillas(Set contenidoCartillas) {
        this.contenidoCartillas = contenidoCartillas;
    }
    public Set getResolucions() {
        return this.resolucions;
    }
    
    public void setResolucions(Set resolucions) {
        this.resolucions = resolucions;
    }




}


