package bo.edu.uto.dea.jhs.persistence;
// Generated 14-abr-2014 4:37:45 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ComisionEvaluadora generated by hbm2java
 */
public class ComisionEvaluadora  implements java.io.Serializable {


     private long idComisionEvaluadora;
     private ComisionEvaluadora comisionEvaluadora;
     private Carrera carrera;
     private Integer gestion;
     private Date fechaInicio;
     private Date fechaFin;
     private String estado;
     private Set comisionEvaluadoras = new HashSet(0);
     private Set miembroComisionEvaluadoras = new HashSet(0);

    public ComisionEvaluadora() {
    }

	
    public ComisionEvaluadora(long idComisionEvaluadora, Carrera carrera) {
        this.idComisionEvaluadora = idComisionEvaluadora;
        this.carrera = carrera;
    }
    public ComisionEvaluadora(long idComisionEvaluadora, ComisionEvaluadora comisionEvaluadora, Carrera carrera, Integer gestion, Date fechaInicio, Date fechaFin, String estado, Set comisionEvaluadoras, Set miembroComisionEvaluadoras) {
       this.idComisionEvaluadora = idComisionEvaluadora;
       this.comisionEvaluadora = comisionEvaluadora;
       this.carrera = carrera;
       this.gestion = gestion;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.estado = estado;
       this.comisionEvaluadoras = comisionEvaluadoras;
       this.miembroComisionEvaluadoras = miembroComisionEvaluadoras;
    }
   
    public long getIdComisionEvaluadora() {
        return this.idComisionEvaluadora;
    }
    
    public void setIdComisionEvaluadora(long idComisionEvaluadora) {
        this.idComisionEvaluadora = idComisionEvaluadora;
    }
    public ComisionEvaluadora getComisionEvaluadora() {
        return this.comisionEvaluadora;
    }
    
    public void setComisionEvaluadora(ComisionEvaluadora comisionEvaluadora) {
        this.comisionEvaluadora = comisionEvaluadora;
    }
    public Carrera getCarrera() {
        return this.carrera;
    }
    
    public void setCarrera(Carrera carrera) {
        this.carrera = carrera;
    }
    public Integer getGestion() {
        return this.gestion;
    }
    
    public void setGestion(Integer gestion) {
        this.gestion = gestion;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getComisionEvaluadoras() {
        return this.comisionEvaluadoras;
    }
    
    public void setComisionEvaluadoras(Set comisionEvaluadoras) {
        this.comisionEvaluadoras = comisionEvaluadoras;
    }
    public Set getMiembroComisionEvaluadoras() {
        return this.miembroComisionEvaluadoras;
    }
    
    public void setMiembroComisionEvaluadoras(Set miembroComisionEvaluadoras) {
        this.miembroComisionEvaluadoras = miembroComisionEvaluadoras;
    }




}


