package bo.edu.uto.dea.jhs.persistence;
// Generated 14-abr-2014 4:37:45 by Hibernate Tools 3.2.1.GA



/**
 * ContenidoCartilla generated by hbm2java
 */
public class ContenidoCartilla  implements java.io.Serializable {


     private long idContenidoCartilla;
     private Evaluacion evaluacion;
     private Cartilla cartilla;
     private int cargaHoraria;
     private double puntajeEvaluacion;
     private double puntajeParcial;

    public ContenidoCartilla() {
    }

    public ContenidoCartilla(long idContenidoCartilla, Evaluacion evaluacion, Cartilla cartilla, int cargaHoraria, double puntajeEvaluacion, double puntajeParcial) {
       this.idContenidoCartilla = idContenidoCartilla;
       this.evaluacion = evaluacion;
       this.cartilla = cartilla;
       this.cargaHoraria = cargaHoraria;
       this.puntajeEvaluacion = puntajeEvaluacion;
       this.puntajeParcial = puntajeParcial;
    }
   
    public long getIdContenidoCartilla() {
        return this.idContenidoCartilla;
    }
    
    public void setIdContenidoCartilla(long idContenidoCartilla) {
        this.idContenidoCartilla = idContenidoCartilla;
    }
    public Evaluacion getEvaluacion() {
        return this.evaluacion;
    }
    
    public void setEvaluacion(Evaluacion evaluacion) {
        this.evaluacion = evaluacion;
    }
    public Cartilla getCartilla() {
        return this.cartilla;
    }
    
    public void setCartilla(Cartilla cartilla) {
        this.cartilla = cartilla;
    }
    public int getCargaHoraria() {
        return this.cargaHoraria;
    }
    
    public void setCargaHoraria(int cargaHoraria) {
        this.cargaHoraria = cargaHoraria;
    }
    public double getPuntajeEvaluacion() {
        return this.puntajeEvaluacion;
    }
    
    public void setPuntajeEvaluacion(double puntajeEvaluacion) {
        this.puntajeEvaluacion = puntajeEvaluacion;
    }
    public double getPuntajeParcial() {
        return this.puntajeParcial;
    }
    
    public void setPuntajeParcial(double puntajeParcial) {
        this.puntajeParcial = puntajeParcial;
    }




}


