package bo.edu.uto.dea.jhs.persistence;
// Generated 27-mar-2014 17:27:00 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Contenido generated by hbm2java
 */
public class Contenido  implements java.io.Serializable {


     private long idContenido;
     private Estructura estructura;
     private Contenido contenidoByIdContenidoPredecesor;
     private Contenido contenidoByIdContenidoCalifica;
     private String pregunta;
     private String tipoDato;
     private String valorDefecto;
     private Double notaDefecto;
     private Double notaMaxima;
     private String ponderacion;
     private String formulaVerificacionRespuesta;
     private Set contenidosForIdContenidoPredecesor = new HashSet(0);
     private Set contenidosForIdContenidoCalifica = new HashSet(0);
     private Set contenidoRespuestas = new HashSet(0);

    public Contenido() {
    }

	
    public Contenido(long idContenido, Estructura estructura, Contenido contenidoByIdContenidoPredecesor, Contenido contenidoByIdContenidoCalifica, String pregunta, String tipoDato, String valorDefecto) {
        this.idContenido = idContenido;
        this.estructura = estructura;
        this.contenidoByIdContenidoPredecesor = contenidoByIdContenidoPredecesor;
        this.contenidoByIdContenidoCalifica = contenidoByIdContenidoCalifica;
        this.pregunta = pregunta;
        this.tipoDato = tipoDato;
        this.valorDefecto = valorDefecto;
    }
    public Contenido(long idContenido, Estructura estructura, Contenido contenidoByIdContenidoPredecesor, Contenido contenidoByIdContenidoCalifica, String pregunta, String tipoDato, String valorDefecto, Double notaDefecto, Double notaMaxima, String ponderacion, String formulaVerificacionRespuesta, Set contenidosForIdContenidoPredecesor, Set contenidosForIdContenidoCalifica, Set contenidoRespuestas) {
       this.idContenido = idContenido;
       this.estructura = estructura;
       this.contenidoByIdContenidoPredecesor = contenidoByIdContenidoPredecesor;
       this.contenidoByIdContenidoCalifica = contenidoByIdContenidoCalifica;
       this.pregunta = pregunta;
       this.tipoDato = tipoDato;
       this.valorDefecto = valorDefecto;
       this.notaDefecto = notaDefecto;
       this.notaMaxima = notaMaxima;
       this.ponderacion = ponderacion;
       this.formulaVerificacionRespuesta = formulaVerificacionRespuesta;
       this.contenidosForIdContenidoPredecesor = contenidosForIdContenidoPredecesor;
       this.contenidosForIdContenidoCalifica = contenidosForIdContenidoCalifica;
       this.contenidoRespuestas = contenidoRespuestas;
    }
   
    public long getIdContenido() {
        return this.idContenido;
    }
    
    public void setIdContenido(long idContenido) {
        this.idContenido = idContenido;
    }
    public Estructura getEstructura() {
        return this.estructura;
    }
    
    public void setEstructura(Estructura estructura) {
        this.estructura = estructura;
    }
    public Contenido getContenidoByIdContenidoPredecesor() {
        return this.contenidoByIdContenidoPredecesor;
    }
    
    public void setContenidoByIdContenidoPredecesor(Contenido contenidoByIdContenidoPredecesor) {
        this.contenidoByIdContenidoPredecesor = contenidoByIdContenidoPredecesor;
    }
    public Contenido getContenidoByIdContenidoCalifica() {
        return this.contenidoByIdContenidoCalifica;
    }
    
    public void setContenidoByIdContenidoCalifica(Contenido contenidoByIdContenidoCalifica) {
        this.contenidoByIdContenidoCalifica = contenidoByIdContenidoCalifica;
    }
    public String getPregunta() {
        return this.pregunta;
    }
    
    public void setPregunta(String pregunta) {
        this.pregunta = pregunta;
    }
    public String getTipoDato() {
        return this.tipoDato;
    }
    
    public void setTipoDato(String tipoDato) {
        this.tipoDato = tipoDato;
    }
    public String getValorDefecto() {
        return this.valorDefecto;
    }
    
    public void setValorDefecto(String valorDefecto) {
        this.valorDefecto = valorDefecto;
    }
    public Double getNotaDefecto() {
        return this.notaDefecto;
    }
    
    public void setNotaDefecto(Double notaDefecto) {
        this.notaDefecto = notaDefecto;
    }
    public Double getNotaMaxima() {
        return this.notaMaxima;
    }
    
    public void setNotaMaxima(Double notaMaxima) {
        this.notaMaxima = notaMaxima;
    }
    public String getPonderacion() {
        return this.ponderacion;
    }
    
    public void setPonderacion(String ponderacion) {
        this.ponderacion = ponderacion;
    }
    public String getFormulaVerificacionRespuesta() {
        return this.formulaVerificacionRespuesta;
    }
    
    public void setFormulaVerificacionRespuesta(String formulaVerificacionRespuesta) {
        this.formulaVerificacionRespuesta = formulaVerificacionRespuesta;
    }
    public Set getContenidosForIdContenidoPredecesor() {
        return this.contenidosForIdContenidoPredecesor;
    }
    
    public void setContenidosForIdContenidoPredecesor(Set contenidosForIdContenidoPredecesor) {
        this.contenidosForIdContenidoPredecesor = contenidosForIdContenidoPredecesor;
    }
    public Set getContenidosForIdContenidoCalifica() {
        return this.contenidosForIdContenidoCalifica;
    }
    
    public void setContenidosForIdContenidoCalifica(Set contenidosForIdContenidoCalifica) {
        this.contenidosForIdContenidoCalifica = contenidosForIdContenidoCalifica;
    }
    public Set getContenidoRespuestas() {
        return this.contenidoRespuestas;
    }
    
    public void setContenidoRespuestas(Set contenidoRespuestas) {
        this.contenidoRespuestas = contenidoRespuestas;
    }




}


