package bo.edu.uto.dea.jhs.persistence;
// Generated 27-mar-2014 17:27:00 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * ContenidoRespuesta generated by hbm2java
 */
public class ContenidoRespuesta  implements java.io.Serializable {


     private long idContenidoRespuesta;
     private ContenidoRespuesta contenidoRespuestaByIdContenidoRespuestaCalifica;
     private ContenidoRespuesta contenidoRespuestaByIdContenidoRespuestaPredecesor;
     private EstructuraRespuesta estructuraRespuesta;
     private Contenido contenido;
     private String respuesta;
     private Double nota;
     private Double calificable;
     private Double respuestaValida;
     private Set contenidoRespuestasForIdContenidoRespuestaPredecesor = new HashSet(0);
     private Set contenidoRespuestasForIdContenidoRespuestaCalifica = new HashSet(0);

    public ContenidoRespuesta() {
    }

	
    public ContenidoRespuesta(long idContenidoRespuesta, EstructuraRespuesta estructuraRespuesta, Contenido contenido, String respuesta) {
        this.idContenidoRespuesta = idContenidoRespuesta;
        this.estructuraRespuesta = estructuraRespuesta;
        this.contenido = contenido;
        this.respuesta = respuesta;
    }
    public ContenidoRespuesta(long idContenidoRespuesta, ContenidoRespuesta contenidoRespuestaByIdContenidoRespuestaCalifica, ContenidoRespuesta contenidoRespuestaByIdContenidoRespuestaPredecesor, EstructuraRespuesta estructuraRespuesta, Contenido contenido, String respuesta, Double nota, Double calificable, Double respuestaValida, Set contenidoRespuestasForIdContenidoRespuestaPredecesor, Set contenidoRespuestasForIdContenidoRespuestaCalifica) {
       this.idContenidoRespuesta = idContenidoRespuesta;
       this.contenidoRespuestaByIdContenidoRespuestaCalifica = contenidoRespuestaByIdContenidoRespuestaCalifica;
       this.contenidoRespuestaByIdContenidoRespuestaPredecesor = contenidoRespuestaByIdContenidoRespuestaPredecesor;
       this.estructuraRespuesta = estructuraRespuesta;
       this.contenido = contenido;
       this.respuesta = respuesta;
       this.nota = nota;
       this.calificable = calificable;
       this.respuestaValida = respuestaValida;
       this.contenidoRespuestasForIdContenidoRespuestaPredecesor = contenidoRespuestasForIdContenidoRespuestaPredecesor;
       this.contenidoRespuestasForIdContenidoRespuestaCalifica = contenidoRespuestasForIdContenidoRespuestaCalifica;
    }
   
    public long getIdContenidoRespuesta() {
        return this.idContenidoRespuesta;
    }
    
    public void setIdContenidoRespuesta(long idContenidoRespuesta) {
        this.idContenidoRespuesta = idContenidoRespuesta;
    }
    public ContenidoRespuesta getContenidoRespuestaByIdContenidoRespuestaCalifica() {
        return this.contenidoRespuestaByIdContenidoRespuestaCalifica;
    }
    
    public void setContenidoRespuestaByIdContenidoRespuestaCalifica(ContenidoRespuesta contenidoRespuestaByIdContenidoRespuestaCalifica) {
        this.contenidoRespuestaByIdContenidoRespuestaCalifica = contenidoRespuestaByIdContenidoRespuestaCalifica;
    }
    public ContenidoRespuesta getContenidoRespuestaByIdContenidoRespuestaPredecesor() {
        return this.contenidoRespuestaByIdContenidoRespuestaPredecesor;
    }
    
    public void setContenidoRespuestaByIdContenidoRespuestaPredecesor(ContenidoRespuesta contenidoRespuestaByIdContenidoRespuestaPredecesor) {
        this.contenidoRespuestaByIdContenidoRespuestaPredecesor = contenidoRespuestaByIdContenidoRespuestaPredecesor;
    }
    public EstructuraRespuesta getEstructuraRespuesta() {
        return this.estructuraRespuesta;
    }
    
    public void setEstructuraRespuesta(EstructuraRespuesta estructuraRespuesta) {
        this.estructuraRespuesta = estructuraRespuesta;
    }
    public Contenido getContenido() {
        return this.contenido;
    }
    
    public void setContenido(Contenido contenido) {
        this.contenido = contenido;
    }
    public String getRespuesta() {
        return this.respuesta;
    }
    
    public void setRespuesta(String respuesta) {
        this.respuesta = respuesta;
    }
    public Double getNota() {
        return this.nota;
    }
    
    public void setNota(Double nota) {
        this.nota = nota;
    }
    public Double getCalificable() {
        return this.calificable;
    }
    
    public void setCalificable(Double calificable) {
        this.calificable = calificable;
    }
    public Double getRespuestaValida() {
        return this.respuestaValida;
    }
    
    public void setRespuestaValida(Double respuestaValida) {
        this.respuestaValida = respuestaValida;
    }
    public Set getContenidoRespuestasForIdContenidoRespuestaPredecesor() {
        return this.contenidoRespuestasForIdContenidoRespuestaPredecesor;
    }
    
    public void setContenidoRespuestasForIdContenidoRespuestaPredecesor(Set contenidoRespuestasForIdContenidoRespuestaPredecesor) {
        this.contenidoRespuestasForIdContenidoRespuestaPredecesor = contenidoRespuestasForIdContenidoRespuestaPredecesor;
    }
    public Set getContenidoRespuestasForIdContenidoRespuestaCalifica() {
        return this.contenidoRespuestasForIdContenidoRespuestaCalifica;
    }
    
    public void setContenidoRespuestasForIdContenidoRespuestaCalifica(Set contenidoRespuestasForIdContenidoRespuestaCalifica) {
        this.contenidoRespuestasForIdContenidoRespuestaCalifica = contenidoRespuestasForIdContenidoRespuestaCalifica;
    }




}


