package bo.edu.uto.dea.jhs.persistence;
// Generated 14-abr-2014 4:37:45 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * CoordinadorDea generated by hbm2java
 */
public class CoordinadorDea  implements java.io.Serializable {


     private long idCoordinadorDea;
     private Persona persona;
     private Date fechaInicio;
     private Date fechaFin;
     private String estado;

    public CoordinadorDea() {
    }

	
    public CoordinadorDea(long idCoordinadorDea, Persona persona, Date fechaInicio, Date fechaFin) {
        this.idCoordinadorDea = idCoordinadorDea;
        this.persona = persona;
        this.fechaInicio = fechaInicio;
        this.fechaFin = fechaFin;
    }
    public CoordinadorDea(long idCoordinadorDea, Persona persona, Date fechaInicio, Date fechaFin, String estado) {
       this.idCoordinadorDea = idCoordinadorDea;
       this.persona = persona;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.estado = estado;
    }
   
    public long getIdCoordinadorDea() {
        return this.idCoordinadorDea;
    }
    
    public void setIdCoordinadorDea(long idCoordinadorDea) {
        this.idCoordinadorDea = idCoordinadorDea;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


