package bo.edu.uto.dea.jhs.persistence;
// Generated 14-abr-2014 4:37:45 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * DirectorCarrera generated by hbm2java
 */
public class DirectorCarrera  implements java.io.Serializable {


     private long idDirectorCarrera;
     private Docente docente;
     private Carrera carrera;
     private Integer gestion;
     private Date fechaInicio;
     private Date fechaFin;
     private String estado;

    public DirectorCarrera() {
    }

	
    public DirectorCarrera(long idDirectorCarrera, Docente docente, Carrera carrera) {
        this.idDirectorCarrera = idDirectorCarrera;
        this.docente = docente;
        this.carrera = carrera;
    }
    public DirectorCarrera(long idDirectorCarrera, Docente docente, Carrera carrera, Integer gestion, Date fechaInicio, Date fechaFin, String estado) {
       this.idDirectorCarrera = idDirectorCarrera;
       this.docente = docente;
       this.carrera = carrera;
       this.gestion = gestion;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.estado = estado;
    }
   
    public long getIdDirectorCarrera() {
        return this.idDirectorCarrera;
    }
    
    public void setIdDirectorCarrera(long idDirectorCarrera) {
        this.idDirectorCarrera = idDirectorCarrera;
    }
    public Docente getDocente() {
        return this.docente;
    }
    
    public void setDocente(Docente docente) {
        this.docente = docente;
    }
    public Carrera getCarrera() {
        return this.carrera;
    }
    
    public void setCarrera(Carrera carrera) {
        this.carrera = carrera;
    }
    public Integer getGestion() {
        return this.gestion;
    }
    
    public void setGestion(Integer gestion) {
        this.gestion = gestion;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


