package bo.edu.uto.dea.jhs.persistence;
// Generated 14-abr-2014 4:37:45 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * DirectorDea generated by hbm2java
 */
public class DirectorDea  implements java.io.Serializable {


     private long idDirectorDea;
     private Docente docente;
     private Date fechaInicio;
     private Date fechaFin;
     private String estado;

    public DirectorDea() {
    }

	
    public DirectorDea(long idDirectorDea, Docente docente, Date fechaInicio, Date fechaFin) {
        this.idDirectorDea = idDirectorDea;
        this.docente = docente;
        this.fechaInicio = fechaInicio;
        this.fechaFin = fechaFin;
    }
    public DirectorDea(long idDirectorDea, Docente docente, Date fechaInicio, Date fechaFin, String estado) {
       this.idDirectorDea = idDirectorDea;
       this.docente = docente;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.estado = estado;
    }
   
    public long getIdDirectorDea() {
        return this.idDirectorDea;
    }
    
    public void setIdDirectorDea(long idDirectorDea) {
        this.idDirectorDea = idDirectorDea;
    }
    public Docente getDocente() {
        return this.docente;
    }
    
    public void setDocente(Docente docente) {
        this.docente = docente;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


