package bo.edu.uto.dea.jhs.persistence;
// Generated 14-abr-2014 4:37:45 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Docente generated by hbm2java
 */
public class Docente  implements java.io.Serializable {


     private String ci;
     private Persona persona;
     private String gradoAcademico;
     private String gradoAcademicoAbreviatura;
     private String estado;
     private Set directorCarreras = new HashSet(0);
     private Set docenteEscalafons = new HashSet(0);
     private Set relacionDocenteMaterias = new HashSet(0);
     private Set directorDeas = new HashSet(0);
     private Set miembroComisionEvaluadoras = new HashSet(0);

    public Docente() {
    }

	
    public Docente(String ci, Persona persona, String gradoAcademico, String gradoAcademicoAbreviatura) {
        this.ci = ci;
        this.persona = persona;
        this.gradoAcademico = gradoAcademico;
        this.gradoAcademicoAbreviatura = gradoAcademicoAbreviatura;
    }
    public Docente(String ci, Persona persona, String gradoAcademico, String gradoAcademicoAbreviatura, String estado, Set directorCarreras, Set docenteEscalafons, Set relacionDocenteMaterias, Set directorDeas, Set miembroComisionEvaluadoras) {
       this.ci = ci;
       this.persona = persona;
       this.gradoAcademico = gradoAcademico;
       this.gradoAcademicoAbreviatura = gradoAcademicoAbreviatura;
       this.estado = estado;
       this.directorCarreras = directorCarreras;
       this.docenteEscalafons = docenteEscalafons;
       this.relacionDocenteMaterias = relacionDocenteMaterias;
       this.directorDeas = directorDeas;
       this.miembroComisionEvaluadoras = miembroComisionEvaluadoras;
    }
   
    public String getCi() {
        return this.ci;
    }
    
    public void setCi(String ci) {
        this.ci = ci;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getGradoAcademico() {
        return this.gradoAcademico;
    }
    
    public void setGradoAcademico(String gradoAcademico) {
        this.gradoAcademico = gradoAcademico;
    }
    public String getGradoAcademicoAbreviatura() {
        return this.gradoAcademicoAbreviatura;
    }
    
    public void setGradoAcademicoAbreviatura(String gradoAcademicoAbreviatura) {
        this.gradoAcademicoAbreviatura = gradoAcademicoAbreviatura;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getDirectorCarreras() {
        return this.directorCarreras;
    }
    
    public void setDirectorCarreras(Set directorCarreras) {
        this.directorCarreras = directorCarreras;
    }
    public Set getDocenteEscalafons() {
        return this.docenteEscalafons;
    }
    
    public void setDocenteEscalafons(Set docenteEscalafons) {
        this.docenteEscalafons = docenteEscalafons;
    }
    public Set getRelacionDocenteMaterias() {
        return this.relacionDocenteMaterias;
    }
    
    public void setRelacionDocenteMaterias(Set relacionDocenteMaterias) {
        this.relacionDocenteMaterias = relacionDocenteMaterias;
    }
    public Set getDirectorDeas() {
        return this.directorDeas;
    }
    
    public void setDirectorDeas(Set directorDeas) {
        this.directorDeas = directorDeas;
    }
    public Set getMiembroComisionEvaluadoras() {
        return this.miembroComisionEvaluadoras;
    }
    
    public void setMiembroComisionEvaluadoras(Set miembroComisionEvaluadoras) {
        this.miembroComisionEvaluadoras = miembroComisionEvaluadoras;
    }




}


