package bo.edu.uto.dea.jhs.persistence;
// Generated 27-mar-2014 17:27:00 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Documento generated by hbm2java
 */
public class Documento  implements java.io.Serializable {


     private long idDocumento;
     private Evaluacion evaluacion;
     private Formulario formulario;
     private Date fechaInicio;
     private Date fechaFin;
     private String estado;
     private Set identificadorRegistroFormularios = new HashSet(0);

    public Documento() {
    }

	
    public Documento(long idDocumento, Evaluacion evaluacion, Formulario formulario, Date fechaInicio, Date fechaFin, String estado) {
        this.idDocumento = idDocumento;
        this.evaluacion = evaluacion;
        this.formulario = formulario;
        this.fechaInicio = fechaInicio;
        this.fechaFin = fechaFin;
        this.estado = estado;
    }
    public Documento(long idDocumento, Evaluacion evaluacion, Formulario formulario, Date fechaInicio, Date fechaFin, String estado, Set identificadorRegistroFormularios) {
       this.idDocumento = idDocumento;
       this.evaluacion = evaluacion;
       this.formulario = formulario;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.estado = estado;
       this.identificadorRegistroFormularios = identificadorRegistroFormularios;
    }
   
    public long getIdDocumento() {
        return this.idDocumento;
    }
    
    public void setIdDocumento(long idDocumento) {
        this.idDocumento = idDocumento;
    }
    public Evaluacion getEvaluacion() {
        return this.evaluacion;
    }
    
    public void setEvaluacion(Evaluacion evaluacion) {
        this.evaluacion = evaluacion;
    }
    public Formulario getFormulario() {
        return this.formulario;
    }
    
    public void setFormulario(Formulario formulario) {
        this.formulario = formulario;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getIdentificadorRegistroFormularios() {
        return this.identificadorRegistroFormularios;
    }
    
    public void setIdentificadorRegistroFormularios(Set identificadorRegistroFormularios) {
        this.identificadorRegistroFormularios = identificadorRegistroFormularios;
    }




}


