package bo.edu.uto.dea.jhs.persistence;
// Generated 14-abr-2014 4:37:45 by Hibernate Tools 3.2.1.GA



/**
 * Escalafon generated by hbm2java
 */
public class Escalafon  implements java.io.Serializable {


     private long idEscalafon;
     private DocenteEscalafon docenteEscalafon;
     private Cartilla cartilla;
     private double puntaje;
     private double puntajeAcumulado;
     private String categoria;
     private String gestion;

    public Escalafon() {
    }

    public Escalafon(long idEscalafon, DocenteEscalafon docenteEscalafon, Cartilla cartilla, double puntaje, double puntajeAcumulado, String categoria, String gestion) {
       this.idEscalafon = idEscalafon;
       this.docenteEscalafon = docenteEscalafon;
       this.cartilla = cartilla;
       this.puntaje = puntaje;
       this.puntajeAcumulado = puntajeAcumulado;
       this.categoria = categoria;
       this.gestion = gestion;
    }
   
    public long getIdEscalafon() {
        return this.idEscalafon;
    }
    
    public void setIdEscalafon(long idEscalafon) {
        this.idEscalafon = idEscalafon;
    }
    public DocenteEscalafon getDocenteEscalafon() {
        return this.docenteEscalafon;
    }
    
    public void setDocenteEscalafon(DocenteEscalafon docenteEscalafon) {
        this.docenteEscalafon = docenteEscalafon;
    }
    public Cartilla getCartilla() {
        return this.cartilla;
    }
    
    public void setCartilla(Cartilla cartilla) {
        this.cartilla = cartilla;
    }
    public double getPuntaje() {
        return this.puntaje;
    }
    
    public void setPuntaje(double puntaje) {
        this.puntaje = puntaje;
    }
    public double getPuntajeAcumulado() {
        return this.puntajeAcumulado;
    }
    
    public void setPuntajeAcumulado(double puntajeAcumulado) {
        this.puntajeAcumulado = puntajeAcumulado;
    }
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }
    public String getGestion() {
        return this.gestion;
    }
    
    public void setGestion(String gestion) {
        this.gestion = gestion;
    }




}


