package bo.edu.uto.dea.jhs.persistence;
// Generated 27-mar-2014 17:27:00 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Estructura generated by hbm2java
 */
public class Estructura  implements java.io.Serializable {


     private long idEstructura;
     private Estructura estructuraByIdEstructuraPredecesor;
     private Formulario formulario;
     private Estructura estructuraByIdEstructuraPadre;
     private String tipo;
     private String hijos;
     private String formato;
     private Set estructurasForIdEstructuraPredecesor = new HashSet(0);
     private Set estructuraRespuestas = new HashSet(0);
     private Set contenidos = new HashSet(0);
     private Set estructurasForIdEstructuraPadre = new HashSet(0);

    public Estructura() {
    }

	
    public Estructura(long idEstructura, Estructura estructuraByIdEstructuraPredecesor, Formulario formulario, Estructura estructuraByIdEstructuraPadre, String tipo, String formato) {
        this.idEstructura = idEstructura;
        this.estructuraByIdEstructuraPredecesor = estructuraByIdEstructuraPredecesor;
        this.formulario = formulario;
        this.estructuraByIdEstructuraPadre = estructuraByIdEstructuraPadre;
        this.tipo = tipo;
        this.formato = formato;
    }
    public Estructura(long idEstructura, Estructura estructuraByIdEstructuraPredecesor, Formulario formulario, Estructura estructuraByIdEstructuraPadre, String tipo, String hijos, String formato, Set estructurasForIdEstructuraPredecesor, Set estructuraRespuestas, Set contenidos, Set estructurasForIdEstructuraPadre) {
       this.idEstructura = idEstructura;
       this.estructuraByIdEstructuraPredecesor = estructuraByIdEstructuraPredecesor;
       this.formulario = formulario;
       this.estructuraByIdEstructuraPadre = estructuraByIdEstructuraPadre;
       this.tipo = tipo;
       this.hijos = hijos;
       this.formato = formato;
       this.estructurasForIdEstructuraPredecesor = estructurasForIdEstructuraPredecesor;
       this.estructuraRespuestas = estructuraRespuestas;
       this.contenidos = contenidos;
       this.estructurasForIdEstructuraPadre = estructurasForIdEstructuraPadre;
    }
   
    public long getIdEstructura() {
        return this.idEstructura;
    }
    
    public void setIdEstructura(long idEstructura) {
        this.idEstructura = idEstructura;
    }
    public Estructura getEstructuraByIdEstructuraPredecesor() {
        return this.estructuraByIdEstructuraPredecesor;
    }
    
    public void setEstructuraByIdEstructuraPredecesor(Estructura estructuraByIdEstructuraPredecesor) {
        this.estructuraByIdEstructuraPredecesor = estructuraByIdEstructuraPredecesor;
    }
    public Formulario getFormulario() {
        return this.formulario;
    }
    
    public void setFormulario(Formulario formulario) {
        this.formulario = formulario;
    }
    public Estructura getEstructuraByIdEstructuraPadre() {
        return this.estructuraByIdEstructuraPadre;
    }
    
    public void setEstructuraByIdEstructuraPadre(Estructura estructuraByIdEstructuraPadre) {
        this.estructuraByIdEstructuraPadre = estructuraByIdEstructuraPadre;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getHijos() {
        return this.hijos;
    }
    
    public void setHijos(String hijos) {
        this.hijos = hijos;
    }
    public String getFormato() {
        return this.formato;
    }
    
    public void setFormato(String formato) {
        this.formato = formato;
    }
    public Set getEstructurasForIdEstructuraPredecesor() {
        return this.estructurasForIdEstructuraPredecesor;
    }
    
    public void setEstructurasForIdEstructuraPredecesor(Set estructurasForIdEstructuraPredecesor) {
        this.estructurasForIdEstructuraPredecesor = estructurasForIdEstructuraPredecesor;
    }
    public Set getEstructuraRespuestas() {
        return this.estructuraRespuestas;
    }
    
    public void setEstructuraRespuestas(Set estructuraRespuestas) {
        this.estructuraRespuestas = estructuraRespuestas;
    }
    public Set getContenidos() {
        return this.contenidos;
    }
    
    public void setContenidos(Set contenidos) {
        this.contenidos = contenidos;
    }
    public Set getEstructurasForIdEstructuraPadre() {
        return this.estructurasForIdEstructuraPadre;
    }
    
    public void setEstructurasForIdEstructuraPadre(Set estructurasForIdEstructuraPadre) {
        this.estructurasForIdEstructuraPadre = estructurasForIdEstructuraPadre;
    }




}


