package bo.edu.uto.dea.jhs.persistence;
// Generated 27-mar-2014 17:27:00 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * EstructuraRespuesta generated by hbm2java
 */
public class EstructuraRespuesta  implements java.io.Serializable {


     private long idEstructuraRespuesta;
     private Estructura estructura;
     private IdentificadorRegistroFormulario identificadorRegistroFormulario;
     private EstructuraRespuesta estructuraRespuestaByIdEstructuraRespuestaPadre;
     private EstructuraRespuesta estructuraRespuestaByIdEstructuraRespuestaPredecesor;
     private String tipo;
     private String hijos;
     private String formato;
     private Set estructuraRespuestasForIdEstructuraRespuestaPadre = new HashSet(0);
     private Set estructuraRespuestasForIdEstructuraRespuestaPredecesor = new HashSet(0);
     private Set contenidoRespuestas = new HashSet(0);

    public EstructuraRespuesta() {
    }

	
    public EstructuraRespuesta(long idEstructuraRespuesta, Estructura estructura, IdentificadorRegistroFormulario identificadorRegistroFormulario, String tipo, String formato) {
        this.idEstructuraRespuesta = idEstructuraRespuesta;
        this.estructura = estructura;
        this.identificadorRegistroFormulario = identificadorRegistroFormulario;
        this.tipo = tipo;
        this.formato = formato;
    }
    public EstructuraRespuesta(long idEstructuraRespuesta, Estructura estructura, IdentificadorRegistroFormulario identificadorRegistroFormulario, EstructuraRespuesta estructuraRespuestaByIdEstructuraRespuestaPadre, EstructuraRespuesta estructuraRespuestaByIdEstructuraRespuestaPredecesor, String tipo, String hijos, String formato, Set estructuraRespuestasForIdEstructuraRespuestaPadre, Set estructuraRespuestasForIdEstructuraRespuestaPredecesor, Set contenidoRespuestas) {
       this.idEstructuraRespuesta = idEstructuraRespuesta;
       this.estructura = estructura;
       this.identificadorRegistroFormulario = identificadorRegistroFormulario;
       this.estructuraRespuestaByIdEstructuraRespuestaPadre = estructuraRespuestaByIdEstructuraRespuestaPadre;
       this.estructuraRespuestaByIdEstructuraRespuestaPredecesor = estructuraRespuestaByIdEstructuraRespuestaPredecesor;
       this.tipo = tipo;
       this.hijos = hijos;
       this.formato = formato;
       this.estructuraRespuestasForIdEstructuraRespuestaPadre = estructuraRespuestasForIdEstructuraRespuestaPadre;
       this.estructuraRespuestasForIdEstructuraRespuestaPredecesor = estructuraRespuestasForIdEstructuraRespuestaPredecesor;
       this.contenidoRespuestas = contenidoRespuestas;
    }
   
    public long getIdEstructuraRespuesta() {
        return this.idEstructuraRespuesta;
    }
    
    public void setIdEstructuraRespuesta(long idEstructuraRespuesta) {
        this.idEstructuraRespuesta = idEstructuraRespuesta;
    }
    public Estructura getEstructura() {
        return this.estructura;
    }
    
    public void setEstructura(Estructura estructura) {
        this.estructura = estructura;
    }
    public IdentificadorRegistroFormulario getIdentificadorRegistroFormulario() {
        return this.identificadorRegistroFormulario;
    }
    
    public void setIdentificadorRegistroFormulario(IdentificadorRegistroFormulario identificadorRegistroFormulario) {
        this.identificadorRegistroFormulario = identificadorRegistroFormulario;
    }
    public EstructuraRespuesta getEstructuraRespuestaByIdEstructuraRespuestaPadre() {
        return this.estructuraRespuestaByIdEstructuraRespuestaPadre;
    }
    
    public void setEstructuraRespuestaByIdEstructuraRespuestaPadre(EstructuraRespuesta estructuraRespuestaByIdEstructuraRespuestaPadre) {
        this.estructuraRespuestaByIdEstructuraRespuestaPadre = estructuraRespuestaByIdEstructuraRespuestaPadre;
    }
    public EstructuraRespuesta getEstructuraRespuestaByIdEstructuraRespuestaPredecesor() {
        return this.estructuraRespuestaByIdEstructuraRespuestaPredecesor;
    }
    
    public void setEstructuraRespuestaByIdEstructuraRespuestaPredecesor(EstructuraRespuesta estructuraRespuestaByIdEstructuraRespuestaPredecesor) {
        this.estructuraRespuestaByIdEstructuraRespuestaPredecesor = estructuraRespuestaByIdEstructuraRespuestaPredecesor;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getHijos() {
        return this.hijos;
    }
    
    public void setHijos(String hijos) {
        this.hijos = hijos;
    }
    public String getFormato() {
        return this.formato;
    }
    
    public void setFormato(String formato) {
        this.formato = formato;
    }
    public Set getEstructuraRespuestasForIdEstructuraRespuestaPadre() {
        return this.estructuraRespuestasForIdEstructuraRespuestaPadre;
    }
    
    public void setEstructuraRespuestasForIdEstructuraRespuestaPadre(Set estructuraRespuestasForIdEstructuraRespuestaPadre) {
        this.estructuraRespuestasForIdEstructuraRespuestaPadre = estructuraRespuestasForIdEstructuraRespuestaPadre;
    }
    public Set getEstructuraRespuestasForIdEstructuraRespuestaPredecesor() {
        return this.estructuraRespuestasForIdEstructuraRespuestaPredecesor;
    }
    
    public void setEstructuraRespuestasForIdEstructuraRespuestaPredecesor(Set estructuraRespuestasForIdEstructuraRespuestaPredecesor) {
        this.estructuraRespuestasForIdEstructuraRespuestaPredecesor = estructuraRespuestasForIdEstructuraRespuestaPredecesor;
    }
    public Set getContenidoRespuestas() {
        return this.contenidoRespuestas;
    }
    
    public void setContenidoRespuestas(Set contenidoRespuestas) {
        this.contenidoRespuestas = contenidoRespuestas;
    }




}


