package bo.edu.uto.dea.jhs.persistence;
// Generated 14-abr-2014 4:37:45 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Estudiante generated by hbm2java
 */
public class Estudiante  implements java.io.Serializable {


     private String ci;
     private Persona persona;
     private String estado;
     private Set relacionEstudianteMaterias = new HashSet(0);

    public Estudiante() {
    }

	
    public Estudiante(String ci, Persona persona) {
        this.ci = ci;
        this.persona = persona;
    }
    public Estudiante(String ci, Persona persona, String estado, Set relacionEstudianteMaterias) {
       this.ci = ci;
       this.persona = persona;
       this.estado = estado;
       this.relacionEstudianteMaterias = relacionEstudianteMaterias;
    }
   
    public String getCi() {
        return this.ci;
    }
    
    public void setCi(String ci) {
        this.ci = ci;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getRelacionEstudianteMaterias() {
        return this.relacionEstudianteMaterias;
    }
    
    public void setRelacionEstudianteMaterias(Set relacionEstudianteMaterias) {
        this.relacionEstudianteMaterias = relacionEstudianteMaterias;
    }




}


