package bo.edu.uto.dea.jhs.persistence;
// Generated 14-abr-2014 4:37:45 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Evaluacion generated by hbm2java
 */
public class Evaluacion  implements java.io.Serializable {


     private long idEvaluacion;
     private RelacionDocenteMateria relacionDocenteMateria;
     private Double nota;
     private Set contenidoCartillas = new HashSet(0);

    public Evaluacion() {
    }

	
    public Evaluacion(long idEvaluacion, RelacionDocenteMateria relacionDocenteMateria) {
        this.idEvaluacion = idEvaluacion;
        this.relacionDocenteMateria = relacionDocenteMateria;
    }
    public Evaluacion(long idEvaluacion, RelacionDocenteMateria relacionDocenteMateria, Double nota, Set contenidoCartillas) {
       this.idEvaluacion = idEvaluacion;
       this.relacionDocenteMateria = relacionDocenteMateria;
       this.nota = nota;
       this.contenidoCartillas = contenidoCartillas;
    }
   
    public long getIdEvaluacion() {
        return this.idEvaluacion;
    }
    
    public void setIdEvaluacion(long idEvaluacion) {
        this.idEvaluacion = idEvaluacion;
    }
    public RelacionDocenteMateria getRelacionDocenteMateria() {
        return this.relacionDocenteMateria;
    }
    
    public void setRelacionDocenteMateria(RelacionDocenteMateria relacionDocenteMateria) {
        this.relacionDocenteMateria = relacionDocenteMateria;
    }
    public Double getNota() {
        return this.nota;
    }
    
    public void setNota(Double nota) {
        this.nota = nota;
    }
    public Set getContenidoCartillas() {
        return this.contenidoCartillas;
    }
    
    public void setContenidoCartillas(Set contenidoCartillas) {
        this.contenidoCartillas = contenidoCartillas;
    }




}


