package bo.edu.uto.dea.jhs.persistence;
// Generated 14-abr-2014 4:37:45 by Hibernate Tools 3.2.1.GA



/**
 * EvaluacionEscalafon generated by hbm2java
 */
public class EvaluacionEscalafon  implements java.io.Serializable {


     private long idEvaluacionEscalafon;
     private Cartilla cartilla;
     private String tipoEvaluacion;
     private String cargo;
     private String lugar;
     private double nota;

    public EvaluacionEscalafon() {
    }

    public EvaluacionEscalafon(long idEvaluacionEscalafon, Cartilla cartilla, String tipoEvaluacion, String cargo, String lugar, double nota) {
       this.idEvaluacionEscalafon = idEvaluacionEscalafon;
       this.cartilla = cartilla;
       this.tipoEvaluacion = tipoEvaluacion;
       this.cargo = cargo;
       this.lugar = lugar;
       this.nota = nota;
    }
   
    public long getIdEvaluacionEscalafon() {
        return this.idEvaluacionEscalafon;
    }
    
    public void setIdEvaluacionEscalafon(long idEvaluacionEscalafon) {
        this.idEvaluacionEscalafon = idEvaluacionEscalafon;
    }
    public Cartilla getCartilla() {
        return this.cartilla;
    }
    
    public void setCartilla(Cartilla cartilla) {
        this.cartilla = cartilla;
    }
    public String getTipoEvaluacion() {
        return this.tipoEvaluacion;
    }
    
    public void setTipoEvaluacion(String tipoEvaluacion) {
        this.tipoEvaluacion = tipoEvaluacion;
    }
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }
    public String getLugar() {
        return this.lugar;
    }
    
    public void setLugar(String lugar) {
        this.lugar = lugar;
    }
    public double getNota() {
        return this.nota;
    }
    
    public void setNota(double nota) {
        this.nota = nota;
    }




}


