package bo.edu.uto.dea.jhs.persistence;
// Generated 27-mar-2014 17:27:00 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Formulario generated by hbm2java
 */
public class Formulario  implements java.io.Serializable {


     private long idFormulario;
     private String nombre;
     private String observaciones;
     private String categoria;
     private String dirigido;
     private boolean eliminado;
     private boolean aprobado;
     private Set estructuras = new HashSet(0);
     private Set documentos = new HashSet(0);

    public Formulario() {
    }

	
    public Formulario(long idFormulario, String nombre, String observaciones, String categoria, String dirigido, boolean eliminado, boolean aprobado) {
        this.idFormulario = idFormulario;
        this.nombre = nombre;
        this.observaciones = observaciones;
        this.categoria = categoria;
        this.dirigido = dirigido;
        this.eliminado = eliminado;
        this.aprobado = aprobado;
    }
    public Formulario(long idFormulario, String nombre, String observaciones, String categoria, String dirigido, boolean eliminado, boolean aprobado, Set estructuras, Set documentos) {
       this.idFormulario = idFormulario;
       this.nombre = nombre;
       this.observaciones = observaciones;
       this.categoria = categoria;
       this.dirigido = dirigido;
       this.eliminado = eliminado;
       this.aprobado = aprobado;
       this.estructuras = estructuras;
       this.documentos = documentos;
    }
   
    public long getIdFormulario() {
        return this.idFormulario;
    }
    
    public void setIdFormulario(long idFormulario) {
        this.idFormulario = idFormulario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }
    public String getDirigido() {
        return this.dirigido;
    }
    
    public void setDirigido(String dirigido) {
        this.dirigido = dirigido;
    }
    public boolean isEliminado() {
        return this.eliminado;
    }
    
    public void setEliminado(boolean eliminado) {
        this.eliminado = eliminado;
    }
    public boolean isAprobado() {
        return this.aprobado;
    }
    
    public void setAprobado(boolean aprobado) {
        this.aprobado = aprobado;
    }
    public Set getEstructuras() {
        return this.estructuras;
    }
    
    public void setEstructuras(Set estructuras) {
        this.estructuras = estructuras;
    }
    public Set getDocumentos() {
        return this.documentos;
    }
    
    public void setDocumentos(Set documentos) {
        this.documentos = documentos;
    }




}


