package bo.edu.uto.dea.jhs.persistence;
// Generated 27-mar-2014 17:27:00 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * IdentificadorRegistroFormulario generated by hbm2java
 */
public class IdentificadorRegistroFormulario  implements java.io.Serializable {


     private long idIdentificadorRegistroFormulario;
     private Documento documento;
     private IdentificadorRegistroMateria identificadorRegistroMateria;
     private Persona persona;
     private Set estructuraRespuestas = new HashSet(0);

    public IdentificadorRegistroFormulario() {
    }

	
    public IdentificadorRegistroFormulario(long idIdentificadorRegistroFormulario, Documento documento, IdentificadorRegistroMateria identificadorRegistroMateria, Persona persona) {
        this.idIdentificadorRegistroFormulario = idIdentificadorRegistroFormulario;
        this.documento = documento;
        this.identificadorRegistroMateria = identificadorRegistroMateria;
        this.persona = persona;
    }
    public IdentificadorRegistroFormulario(long idIdentificadorRegistroFormulario, Documento documento, IdentificadorRegistroMateria identificadorRegistroMateria, Persona persona, Set estructuraRespuestas) {
       this.idIdentificadorRegistroFormulario = idIdentificadorRegistroFormulario;
       this.documento = documento;
       this.identificadorRegistroMateria = identificadorRegistroMateria;
       this.persona = persona;
       this.estructuraRespuestas = estructuraRespuestas;
    }
   
    public long getIdIdentificadorRegistroFormulario() {
        return this.idIdentificadorRegistroFormulario;
    }
    
    public void setIdIdentificadorRegistroFormulario(long idIdentificadorRegistroFormulario) {
        this.idIdentificadorRegistroFormulario = idIdentificadorRegistroFormulario;
    }
    public Documento getDocumento() {
        return this.documento;
    }
    
    public void setDocumento(Documento documento) {
        this.documento = documento;
    }
    public IdentificadorRegistroMateria getIdentificadorRegistroMateria() {
        return this.identificadorRegistroMateria;
    }
    
    public void setIdentificadorRegistroMateria(IdentificadorRegistroMateria identificadorRegistroMateria) {
        this.identificadorRegistroMateria = identificadorRegistroMateria;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public Set getEstructuraRespuestas() {
        return this.estructuraRespuestas;
    }
    
    public void setEstructuraRespuestas(Set estructuraRespuestas) {
        this.estructuraRespuestas = estructuraRespuestas;
    }




}


