package bo.edu.uto.dea.jhs.persistence;
// Generated 14-abr-2014 4:37:45 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * IdentificadorRegistroMateria generated by hbm2java
 */
public class IdentificadorRegistroMateria  implements java.io.Serializable {


     private long idIdentificadorRegistroMateria;
     private Set relacionEstudianteMaterias = new HashSet(0);
     private Set relacionDocenteMaterias = new HashSet(0);

    public IdentificadorRegistroMateria() {
    }

	
    public IdentificadorRegistroMateria(long idIdentificadorRegistroMateria) {
        this.idIdentificadorRegistroMateria = idIdentificadorRegistroMateria;
    }
    public IdentificadorRegistroMateria(long idIdentificadorRegistroMateria, Set relacionEstudianteMaterias, Set relacionDocenteMaterias) {
       this.idIdentificadorRegistroMateria = idIdentificadorRegistroMateria;
       this.relacionEstudianteMaterias = relacionEstudianteMaterias;
       this.relacionDocenteMaterias = relacionDocenteMaterias;
    }
   
    public long getIdIdentificadorRegistroMateria() {
        return this.idIdentificadorRegistroMateria;
    }
    
    public void setIdIdentificadorRegistroMateria(long idIdentificadorRegistroMateria) {
        this.idIdentificadorRegistroMateria = idIdentificadorRegistroMateria;
    }
    public Set getRelacionEstudianteMaterias() {
        return this.relacionEstudianteMaterias;
    }
    
    public void setRelacionEstudianteMaterias(Set relacionEstudianteMaterias) {
        this.relacionEstudianteMaterias = relacionEstudianteMaterias;
    }
    public Set getRelacionDocenteMaterias() {
        return this.relacionDocenteMaterias;
    }
    
    public void setRelacionDocenteMaterias(Set relacionDocenteMaterias) {
        this.relacionDocenteMaterias = relacionDocenteMaterias;
    }




}


