package bo.edu.uto.dea.jhs.persistence;
// Generated 14-abr-2014 4:37:45 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Materia generated by hbm2java
 */
public class Materia  implements java.io.Serializable {


     private long idMateria;
     private Carrera carrera;
     private String siglaMateria;
     private String nombre;
     private String estado;
     private Set requiereMateriasForIdMateriaRequisito = new HashSet(0);
     private Set requiereMateriasForIdMateria = new HashSet(0);
     private Set relacionDocenteMaterias = new HashSet(0);

    public Materia() {
    }

	
    public Materia(long idMateria, Carrera carrera, String siglaMateria) {
        this.idMateria = idMateria;
        this.carrera = carrera;
        this.siglaMateria = siglaMateria;
    }
    public Materia(long idMateria, Carrera carrera, String siglaMateria, String nombre, String estado, Set requiereMateriasForIdMateriaRequisito, Set requiereMateriasForIdMateria, Set relacionDocenteMaterias) {
       this.idMateria = idMateria;
       this.carrera = carrera;
       this.siglaMateria = siglaMateria;
       this.nombre = nombre;
       this.estado = estado;
       this.requiereMateriasForIdMateriaRequisito = requiereMateriasForIdMateriaRequisito;
       this.requiereMateriasForIdMateria = requiereMateriasForIdMateria;
       this.relacionDocenteMaterias = relacionDocenteMaterias;
    }
   
    public long getIdMateria() {
        return this.idMateria;
    }
    
    public void setIdMateria(long idMateria) {
        this.idMateria = idMateria;
    }
    public Carrera getCarrera() {
        return this.carrera;
    }
    
    public void setCarrera(Carrera carrera) {
        this.carrera = carrera;
    }
    public String getSiglaMateria() {
        return this.siglaMateria;
    }
    
    public void setSiglaMateria(String siglaMateria) {
        this.siglaMateria = siglaMateria;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getRequiereMateriasForIdMateriaRequisito() {
        return this.requiereMateriasForIdMateriaRequisito;
    }
    
    public void setRequiereMateriasForIdMateriaRequisito(Set requiereMateriasForIdMateriaRequisito) {
        this.requiereMateriasForIdMateriaRequisito = requiereMateriasForIdMateriaRequisito;
    }
    public Set getRequiereMateriasForIdMateria() {
        return this.requiereMateriasForIdMateria;
    }
    
    public void setRequiereMateriasForIdMateria(Set requiereMateriasForIdMateria) {
        this.requiereMateriasForIdMateria = requiereMateriasForIdMateria;
    }
    public Set getRelacionDocenteMaterias() {
        return this.relacionDocenteMaterias;
    }
    
    public void setRelacionDocenteMaterias(Set relacionDocenteMaterias) {
        this.relacionDocenteMaterias = relacionDocenteMaterias;
    }




}


