package bo.edu.uto.dea.jhs.persistence;
// Generated 14-abr-2014 4:37:45 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * MiembroComisionEvaluadora generated by hbm2java
 */
public class MiembroComisionEvaluadora  implements java.io.Serializable {


     private String ci;
     private Docente docente;
     private ComisionEvaluadora comisionEvaluadora;
     private long idMiembroComisionEvaluadora;
     private Date fechaInicio;
     private Date fechaFin;
     private String estado;

    public MiembroComisionEvaluadora() {
    }

	
    public MiembroComisionEvaluadora(String ci, Docente docente, ComisionEvaluadora comisionEvaluadora, long idMiembroComisionEvaluadora) {
        this.ci = ci;
        this.docente = docente;
        this.comisionEvaluadora = comisionEvaluadora;
        this.idMiembroComisionEvaluadora = idMiembroComisionEvaluadora;
    }
    public MiembroComisionEvaluadora(String ci, Docente docente, ComisionEvaluadora comisionEvaluadora, long idMiembroComisionEvaluadora, Date fechaInicio, Date fechaFin, String estado) {
       this.ci = ci;
       this.docente = docente;
       this.comisionEvaluadora = comisionEvaluadora;
       this.idMiembroComisionEvaluadora = idMiembroComisionEvaluadora;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.estado = estado;
    }
   
    public String getCi() {
        return this.ci;
    }
    
    public void setCi(String ci) {
        this.ci = ci;
    }
    public Docente getDocente() {
        return this.docente;
    }
    
    public void setDocente(Docente docente) {
        this.docente = docente;
    }
    public ComisionEvaluadora getComisionEvaluadora() {
        return this.comisionEvaluadora;
    }
    
    public void setComisionEvaluadora(ComisionEvaluadora comisionEvaluadora) {
        this.comisionEvaluadora = comisionEvaluadora;
    }
    public long getIdMiembroComisionEvaluadora() {
        return this.idMiembroComisionEvaluadora;
    }
    
    public void setIdMiembroComisionEvaluadora(long idMiembroComisionEvaluadora) {
        this.idMiembroComisionEvaluadora = idMiembroComisionEvaluadora;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


