package bo.edu.uto.dea.jhs.persistence;
// Generated 14-abr-2014 4:37:45 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private String ci;
     private String nombre;
     private String app;
     private String apm;
     private String cuenta;
     private String contrasenia;
     private String estado;
     private Set estudiantes = new HashSet(0);
     private Set coordinadorDeas = new HashSet(0);
     private Set docentes = new HashSet(0);

    public Persona() {
    }

	
    public Persona(String ci) {
        this.ci = ci;
    }
    public Persona(String ci, String nombre, String app, String apm, String cuenta, String contrasenia, String estado, Set estudiantes, Set coordinadorDeas, Set docentes) {
       this.ci = ci;
       this.nombre = nombre;
       this.app = app;
       this.apm = apm;
       this.cuenta = cuenta;
       this.contrasenia = contrasenia;
       this.estado = estado;
       this.estudiantes = estudiantes;
       this.coordinadorDeas = coordinadorDeas;
       this.docentes = docentes;
    }
   
    public String getCi() {
        return this.ci;
    }
    
    public void setCi(String ci) {
        this.ci = ci;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApp() {
        return this.app;
    }
    
    public void setApp(String app) {
        this.app = app;
    }
    public String getApm() {
        return this.apm;
    }
    
    public void setApm(String apm) {
        this.apm = apm;
    }
    public String getCuenta() {
        return this.cuenta;
    }
    
    public void setCuenta(String cuenta) {
        this.cuenta = cuenta;
    }
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getEstudiantes() {
        return this.estudiantes;
    }
    
    public void setEstudiantes(Set estudiantes) {
        this.estudiantes = estudiantes;
    }
    public Set getCoordinadorDeas() {
        return this.coordinadorDeas;
    }
    
    public void setCoordinadorDeas(Set coordinadorDeas) {
        this.coordinadorDeas = coordinadorDeas;
    }
    public Set getDocentes() {
        return this.docentes;
    }
    
    public void setDocentes(Set docentes) {
        this.docentes = docentes;
    }




}


