package bo.edu.uto.dea.jhs.persistence;
// Generated 14-abr-2014 4:37:45 by Hibernate Tools 3.2.1.GA



/**
 * RelacionEstudianteMateria generated by hbm2java
 */
public class RelacionEstudianteMateria  implements java.io.Serializable {


     private long idRelacionEstudianteMateria;
     private RelacionDocenteMateria relacionDocenteMateria;
     private Estudiante estudiante;
     private IdentificadorRegistroMateria identificadorRegistroMateria;

    public RelacionEstudianteMateria() {
    }

    public RelacionEstudianteMateria(long idRelacionEstudianteMateria, RelacionDocenteMateria relacionDocenteMateria, Estudiante estudiante, IdentificadorRegistroMateria identificadorRegistroMateria) {
       this.idRelacionEstudianteMateria = idRelacionEstudianteMateria;
       this.relacionDocenteMateria = relacionDocenteMateria;
       this.estudiante = estudiante;
       this.identificadorRegistroMateria = identificadorRegistroMateria;
    }
   
    public long getIdRelacionEstudianteMateria() {
        return this.idRelacionEstudianteMateria;
    }
    
    public void setIdRelacionEstudianteMateria(long idRelacionEstudianteMateria) {
        this.idRelacionEstudianteMateria = idRelacionEstudianteMateria;
    }
    public RelacionDocenteMateria getRelacionDocenteMateria() {
        return this.relacionDocenteMateria;
    }
    
    public void setRelacionDocenteMateria(RelacionDocenteMateria relacionDocenteMateria) {
        this.relacionDocenteMateria = relacionDocenteMateria;
    }
    public Estudiante getEstudiante() {
        return this.estudiante;
    }
    
    public void setEstudiante(Estudiante estudiante) {
        this.estudiante = estudiante;
    }
    public IdentificadorRegistroMateria getIdentificadorRegistroMateria() {
        return this.identificadorRegistroMateria;
    }
    
    public void setIdentificadorRegistroMateria(IdentificadorRegistroMateria identificadorRegistroMateria) {
        this.identificadorRegistroMateria = identificadorRegistroMateria;
    }




}


