package bo.edu.uto.dea.jhs.persistence;
// Generated 14-abr-2014 4:37:45 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * RelacionDocenteMateria generated by hbm2java
 */
public class RelacionDocenteMateria  implements java.io.Serializable {


     private long idRelacionDocenteMateria;
     private IdentificadorRegistroMateria identificadorRegistroMateria;
     private Materia materia;
     private Docente docente;
     private String paralelo;
     private String periodo;
     private String tipoPeriodo;
     private Integer gestion;
     private Date fechaInicio;
     private Date fechaFin;
     private int horas;
     private String item;
     private String tipoMateria;
     private String estado;
     private Set evaluacions = new HashSet(0);
     private Set relacionEstudianteMaterias = new HashSet(0);

    public RelacionDocenteMateria() {
    }

	
    public RelacionDocenteMateria(long idRelacionDocenteMateria, IdentificadorRegistroMateria identificadorRegistroMateria, Materia materia, Docente docente, String paralelo, String periodo, String tipoPeriodo, Date fechaInicio, Date fechaFin, int horas, String item, String tipoMateria, String estado) {
        this.idRelacionDocenteMateria = idRelacionDocenteMateria;
        this.identificadorRegistroMateria = identificadorRegistroMateria;
        this.materia = materia;
        this.docente = docente;
        this.paralelo = paralelo;
        this.periodo = periodo;
        this.tipoPeriodo = tipoPeriodo;
        this.fechaInicio = fechaInicio;
        this.fechaFin = fechaFin;
        this.horas = horas;
        this.item = item;
        this.tipoMateria = tipoMateria;
        this.estado = estado;
    }
    public RelacionDocenteMateria(long idRelacionDocenteMateria, IdentificadorRegistroMateria identificadorRegistroMateria, Materia materia, Docente docente, String paralelo, String periodo, String tipoPeriodo, Integer gestion, Date fechaInicio, Date fechaFin, int horas, String item, String tipoMateria, String estado, Set evaluacions, Set relacionEstudianteMaterias) {
       this.idRelacionDocenteMateria = idRelacionDocenteMateria;
       this.identificadorRegistroMateria = identificadorRegistroMateria;
       this.materia = materia;
       this.docente = docente;
       this.paralelo = paralelo;
       this.periodo = periodo;
       this.tipoPeriodo = tipoPeriodo;
       this.gestion = gestion;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.horas = horas;
       this.item = item;
       this.tipoMateria = tipoMateria;
       this.estado = estado;
       this.evaluacions = evaluacions;
       this.relacionEstudianteMaterias = relacionEstudianteMaterias;
    }
   
    public long getIdRelacionDocenteMateria() {
        return this.idRelacionDocenteMateria;
    }
    
    public void setIdRelacionDocenteMateria(long idRelacionDocenteMateria) {
        this.idRelacionDocenteMateria = idRelacionDocenteMateria;
    }
    public IdentificadorRegistroMateria getIdentificadorRegistroMateria() {
        return this.identificadorRegistroMateria;
    }
    
    public void setIdentificadorRegistroMateria(IdentificadorRegistroMateria identificadorRegistroMateria) {
        this.identificadorRegistroMateria = identificadorRegistroMateria;
    }
    public Materia getMateria() {
        return this.materia;
    }
    
    public void setMateria(Materia materia) {
        this.materia = materia;
    }
    public Docente getDocente() {
        return this.docente;
    }
    
    public void setDocente(Docente docente) {
        this.docente = docente;
    }
    public String getParalelo() {
        return this.paralelo;
    }
    
    public void setParalelo(String paralelo) {
        this.paralelo = paralelo;
    }
    public String getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(String periodo) {
        this.periodo = periodo;
    }
    public String getTipoPeriodo() {
        return this.tipoPeriodo;
    }
    
    public void setTipoPeriodo(String tipoPeriodo) {
        this.tipoPeriodo = tipoPeriodo;
    }
    public Integer getGestion() {
        return this.gestion;
    }
    
    public void setGestion(Integer gestion) {
        this.gestion = gestion;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
    public int getHoras() {
        return this.horas;
    }
    
    public void setHoras(int horas) {
        this.horas = horas;
    }
    public String getItem() {
        return this.item;
    }
    
    public void setItem(String item) {
        this.item = item;
    }
    public String getTipoMateria() {
        return this.tipoMateria;
    }
    
    public void setTipoMateria(String tipoMateria) {
        this.tipoMateria = tipoMateria;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getEvaluacions() {
        return this.evaluacions;
    }
    
    public void setEvaluacions(Set evaluacions) {
        this.evaluacions = evaluacions;
    }
    public Set getRelacionEstudianteMaterias() {
        return this.relacionEstudianteMaterias;
    }
    
    public void setRelacionEstudianteMaterias(Set relacionEstudianteMaterias) {
        this.relacionEstudianteMaterias = relacionEstudianteMaterias;
    }




}


