package bo.edu.uto.dea.jhs.persistence;
// Generated 14-abr-2014 4:37:45 by Hibernate Tools 3.2.1.GA



/**
 * RequiereMateria generated by hbm2java
 */
public class RequiereMateria  implements java.io.Serializable {


     private long idRequiereMateria;
     private Materia materiaByIdMateria;
     private Materia materiaByIdMateriaRequisito;

    public RequiereMateria() {
    }

    public RequiereMateria(long idRequiereMateria, Materia materiaByIdMateria, Materia materiaByIdMateriaRequisito) {
       this.idRequiereMateria = idRequiereMateria;
       this.materiaByIdMateria = materiaByIdMateria;
       this.materiaByIdMateriaRequisito = materiaByIdMateriaRequisito;
    }
   
    public long getIdRequiereMateria() {
        return this.idRequiereMateria;
    }
    
    public void setIdRequiereMateria(long idRequiereMateria) {
        this.idRequiereMateria = idRequiereMateria;
    }
    public Materia getMateriaByIdMateria() {
        return this.materiaByIdMateria;
    }
    
    public void setMateriaByIdMateria(Materia materiaByIdMateria) {
        this.materiaByIdMateria = materiaByIdMateria;
    }
    public Materia getMateriaByIdMateriaRequisito() {
        return this.materiaByIdMateriaRequisito;
    }
    
    public void setMateriaByIdMateriaRequisito(Materia materiaByIdMateriaRequisito) {
        this.materiaByIdMateriaRequisito = materiaByIdMateriaRequisito;
    }




}


