package bo.edu.uto.dea.jhs.persistence;
// Generated 14-abr-2014 4:37:45 by Hibernate Tools 3.2.1.GA



/**
 * Resolucion generated by hbm2java
 */
public class Resolucion  implements java.io.Serializable {


     private long idResolucion;
     private Cartilla cartilla;
     private String contenido;
     private String gestion;
     private double puntajeEscalafon;
     private double puntajeAcumulado;
     private String categoria;
     private String tipoResolucion;

    public Resolucion() {
    }

    public Resolucion(long idResolucion, Cartilla cartilla, String contenido, String gestion, double puntajeEscalafon, double puntajeAcumulado, String categoria, String tipoResolucion) {
       this.idResolucion = idResolucion;
       this.cartilla = cartilla;
       this.contenido = contenido;
       this.gestion = gestion;
       this.puntajeEscalafon = puntajeEscalafon;
       this.puntajeAcumulado = puntajeAcumulado;
       this.categoria = categoria;
       this.tipoResolucion = tipoResolucion;
    }
   
    public long getIdResolucion() {
        return this.idResolucion;
    }
    
    public void setIdResolucion(long idResolucion) {
        this.idResolucion = idResolucion;
    }
    public Cartilla getCartilla() {
        return this.cartilla;
    }
    
    public void setCartilla(Cartilla cartilla) {
        this.cartilla = cartilla;
    }
    public String getContenido() {
        return this.contenido;
    }
    
    public void setContenido(String contenido) {
        this.contenido = contenido;
    }
    public String getGestion() {
        return this.gestion;
    }
    
    public void setGestion(String gestion) {
        this.gestion = gestion;
    }
    public double getPuntajeEscalafon() {
        return this.puntajeEscalafon;
    }
    
    public void setPuntajeEscalafon(double puntajeEscalafon) {
        this.puntajeEscalafon = puntajeEscalafon;
    }
    public double getPuntajeAcumulado() {
        return this.puntajeAcumulado;
    }
    
    public void setPuntajeAcumulado(double puntajeAcumulado) {
        this.puntajeAcumulado = puntajeAcumulado;
    }
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }
    public String getTipoResolucion() {
        return this.tipoResolucion;
    }
    
    public void setTipoResolucion(String tipoResolucion) {
        this.tipoResolucion = tipoResolucion;
    }




}


