package bo.edu.uto.dea.jhs.persistence;
// Generated 14-abr-2014 4:37:45 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Universidad generated by hbm2java
 */
public class Universidad  implements java.io.Serializable {


     private String siglaUniversidad;
     private String nombre;
     private String estado;
     private Set facultads = new HashSet(0);

    public Universidad() {
    }

	
    public Universidad(String siglaUniversidad, String nombre, String estado) {
        this.siglaUniversidad = siglaUniversidad;
        this.nombre = nombre;
        this.estado = estado;
    }
    public Universidad(String siglaUniversidad, String nombre, String estado, Set facultads) {
       this.siglaUniversidad = siglaUniversidad;
       this.nombre = nombre;
       this.estado = estado;
       this.facultads = facultads;
    }
   
    public String getSiglaUniversidad() {
        return this.siglaUniversidad;
    }
    
    public void setSiglaUniversidad(String siglaUniversidad) {
        this.siglaUniversidad = siglaUniversidad;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getFacultads() {
        return this.facultads;
    }
    
    public void setFacultads(Set facultads) {
        this.facultads = facultads;
    }




}


