package dea.modelo;
// Generated 16-may-2015 14:51:40 by Hibernate Tools 4.3.1

import java.util.Date;




/**
 * AdministradorDirector generated by hbm2java
 */
public class AdministradorDirector  implements java.io.Serializable {


     private String ci;
     private Persona persona;
     private String estado;
     private Date fechaInicio;
     private Date fechaFin;
    public AdministradorDirector() {
    }

	
    public AdministradorDirector(Persona persona) {
        this.persona = persona;
    }
    public AdministradorDirector(Persona persona, String estado) {
       this.persona = persona;
       this.estado = estado;
    }
   
    public String getCi() {
        return this.ci;
    }
    
    public void setCi(String ci) {
        this.ci = ci;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

    /**
     * @return the fechaInicio
     */
    public Date getFechaInicio() {
        return fechaInicio;
    }

    /**
     * @param fechaInicio the fechaInicio to set
     */
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    /**
     * @return the fechaFin
     */
    public Date getFechaFin() {
        return fechaFin;
    }

    /**
     * @param fechaFin the fechaFin to set
     */
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }




}


