package dea.modelo;
// Generated 16-may-2015 14:51:40 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cartilla generated by hbm2java
 */
public class Cartilla  implements java.io.Serializable {


     private long idCartilla;
     private DocenteEscalafon docenteEscalafon;
     private double totalHoras;
     private double totalParcial;
     private double notaPromedio;
     private double puntajeEscalafon;
     private String gestion;
     private Set contenidoCartillas = new HashSet(0);
     private Set escalafons = new HashSet(0);

    public Cartilla() {
    }

	
    public Cartilla(long idCartilla, DocenteEscalafon docenteEscalafon, double totalHoras, double totalParcial, double notaPromedio, double puntajeEscalafon, String gestion) {
        this.idCartilla = idCartilla;
        this.docenteEscalafon = docenteEscalafon;
        this.totalHoras = totalHoras;
        this.totalParcial = totalParcial;
        this.notaPromedio = notaPromedio;
        this.puntajeEscalafon = puntajeEscalafon;
        this.gestion = gestion;
    }
    public Cartilla(long idCartilla, DocenteEscalafon docenteEscalafon, double totalHoras, double totalParcial, double notaPromedio, double puntajeEscalafon, String gestion, Set contenidoCartillas, Set escalafons) {
       this.idCartilla = idCartilla;
       this.docenteEscalafon = docenteEscalafon;
       this.totalHoras = totalHoras;
       this.totalParcial = totalParcial;
       this.notaPromedio = notaPromedio;
       this.puntajeEscalafon = puntajeEscalafon;
       this.gestion = gestion;
       this.contenidoCartillas = contenidoCartillas;
       this.escalafons = escalafons;
    }
   
    public long getIdCartilla() {
        return this.idCartilla;
    }
    
    public void setIdCartilla(long idCartilla) {
        this.idCartilla = idCartilla;
    }
    public DocenteEscalafon getDocenteEscalafon() {
        return this.docenteEscalafon;
    }
    
    public void setDocenteEscalafon(DocenteEscalafon docenteEscalafon) {
        this.docenteEscalafon = docenteEscalafon;
    }
    public double getTotalHoras() {
        return this.totalHoras;
    }
    
    public void setTotalHoras(double totalHoras) {
        this.totalHoras = totalHoras;
    }
    public double getTotalParcial() {
        return this.totalParcial;
    }
    
    public void setTotalParcial(double totalParcial) {
        this.totalParcial = totalParcial;
    }
    public double getNotaPromedio() {
        return this.notaPromedio;
    }
    
    public void setNotaPromedio(double notaPromedio) {
        this.notaPromedio = notaPromedio;
    }
    public double getPuntajeEscalafon() {
        return this.puntajeEscalafon;
    }
    
    public void setPuntajeEscalafon(double puntajeEscalafon) {
        this.puntajeEscalafon = puntajeEscalafon;
    }
    public String getGestion() {
        return this.gestion;
    }
    
    public void setGestion(String gestion) {
        this.gestion = gestion;
    }
    public Set getContenidoCartillas() {
        return this.contenidoCartillas;
    }
    
    public void setContenidoCartillas(Set contenidoCartillas) {
        this.contenidoCartillas = contenidoCartillas;
    }
    public Set getEscalafons() {
        return this.escalafons;
    }
    
    public void setEscalafons(Set escalafons) {
        this.escalafons = escalafons;
    }




}


