package dea.modelo;
// Generated 16-may-2015 14:51:40 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DocenteRegistroMateria generated by hbm2java
 */
public class DocenteRegistroMateria  implements java.io.Serializable {


     private long idDocenteRegistroMateria;
     private Docente docente;     
     private Materia materia;
     private String paralelo;
     private String periodo;
     private String tipoPeriodo;
     private String gestion;
     private Date fechaInicio;
     private Date fechaFin;
     private short horas;
     private String item;
     private String tipoMateria;
     private String estado;
     private Set estudianteRegistroMaterias = new HashSet(0);
     private Set evaluacions = new HashSet(0);

    public DocenteRegistroMateria() {
    }

	
    public DocenteRegistroMateria(Docente docente, Materia materia, String paralelo, String periodo, String tipoPeriodo, String gestion, Date fechaInicio, Date fechaFin, short horas, String item, String tipoMateria, String estado) {
        this.docente = docente;        
        this.materia = materia;
        this.paralelo = paralelo;
        this.periodo = periodo;
        this.tipoPeriodo = tipoPeriodo;
        this.gestion = gestion;
        this.fechaInicio = fechaInicio;
        this.fechaFin = fechaFin;
        this.horas = horas;
        this.item = item;
        this.tipoMateria = tipoMateria;
        this.estado = estado;
    }
    public DocenteRegistroMateria(Docente docente, Materia materia, String paralelo, String periodo, String tipoPeriodo, String gestion, Date fechaInicio, Date fechaFin, short horas, String item, String tipoMateria, String estado, Set estudianteRegistroMaterias, Set evaluacions) {
       this.docente = docente;
       
       this.materia = materia;
       this.paralelo = paralelo;
       this.periodo = periodo;
       this.tipoPeriodo = tipoPeriodo;
       this.gestion = gestion;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.horas = horas;
       this.item = item;
       this.tipoMateria = tipoMateria;
       this.estado = estado;
       this.estudianteRegistroMaterias = estudianteRegistroMaterias;
       this.evaluacions = evaluacions;
    }
   
    public long getIdDocenteRegistroMateria() {
        return this.idDocenteRegistroMateria;
    }
    
    public void setIdDocenteRegistroMateria(long idDocenteRegistroMateria) {
        this.idDocenteRegistroMateria = idDocenteRegistroMateria;
    }
    public Docente getDocente() {
        return this.docente;
    }
    
    public void setDocente(Docente docente) {
        this.docente = docente;
    }    
    public Materia getMateria() {
        return this.materia;
    }
    
    public void setMateria(Materia materia) {
        this.materia = materia;
    }
    public String getParalelo() {
        return this.paralelo;
    }
    
    public void setParalelo(String paralelo) {
        this.paralelo = paralelo;
    }
    public String getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(String periodo) {
        this.periodo = periodo;
    }
    public String getTipoPeriodo() {
        return this.tipoPeriodo;
    }
    
    public void setTipoPeriodo(String tipoPeriodo) {
        this.tipoPeriodo = tipoPeriodo;
    }
    public String getGestion() {
        return this.gestion;
    }
    
    public void setGestion(String gestion) {
        this.gestion = gestion;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
    public short getHoras() {
        return this.horas;
    }
    
    public void setHoras(short horas) {
        this.horas = horas;
    }
    public String getItem() {
        return this.item;
    }
    
    public void setItem(String item) {
        this.item = item;
    }
    public String getTipoMateria() {
        return this.tipoMateria;
    }
    
    public void setTipoMateria(String tipoMateria) {
        this.tipoMateria = tipoMateria;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getEstudianteRegistroMaterias() {
        return this.estudianteRegistroMaterias;
    }
    
    public void setEstudianteRegistroMaterias(Set estudianteRegistroMaterias) {
        this.estudianteRegistroMaterias = estudianteRegistroMaterias;
    }
    public Set getEvaluacions() {
        return this.evaluacions;
    }
    
    public void setEvaluacions(Set evaluacions) {
        this.evaluacions = evaluacions;
    }




}


