package dea.modelo;
// Generated 16-may-2015 14:51:40 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Docente generated by hbm2java
 */
public class Docente  implements java.io.Serializable {


     private String ci;
     private Persona persona;
     private String gradoAcademico;
     private String estado;
     private DocenteEscalafon docenteEscalafon;
     private Set docenteRegistroMaterias = new HashSet(0);

    public Docente() {
    }

	
    public Docente(Persona persona) {
        this.persona = persona;
    }
    public Docente(Persona persona, String gradoAcademico, String estado, DocenteEscalafon docenteEscalafon, Set docenteRegistroMaterias) {
       this.persona = persona;
       this.gradoAcademico = gradoAcademico;
       this.estado = estado;
       this.docenteEscalafon = docenteEscalafon;
       this.docenteRegistroMaterias = docenteRegistroMaterias;
    }
   
    public String getCi() {
        return this.ci;
    }
    
    public void setCi(String ci) {
        this.ci = ci;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getGradoAcademico() {
        return this.gradoAcademico;
    }
    
    public void setGradoAcademico(String gradoAcademico) {
        this.gradoAcademico = gradoAcademico;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public DocenteEscalafon getDocenteEscalafon() {
        return this.docenteEscalafon;
    }
    
    public void setDocenteEscalafon(DocenteEscalafon docenteEscalafon) {
        this.docenteEscalafon = docenteEscalafon;
    }
    public Set getDocenteRegistroMaterias() {
        return this.docenteRegistroMaterias;
    }
    
    public void setDocenteRegistroMaterias(Set docenteRegistroMaterias) {
        this.docenteRegistroMaterias = docenteRegistroMaterias;
    }




}


