package dea.modelo;
// Generated 16-may-2015 14:51:40 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DocenteEscalafon generated by hbm2java
 */
public class DocenteEscalafon  implements java.io.Serializable {


     private String ci;
     private Carrera carrera;
     private Docente docente;
     private Date fechaNacimiento;
     private String correoElectronico;
     private String tipo;
     private Set escalafons = new HashSet(0);
     private Set cartillas = new HashSet(0);

    public DocenteEscalafon() {
    }

	
    public DocenteEscalafon(Carrera carrera, Docente docente) {
        this.carrera = carrera;
        this.docente = docente;
    }
    public DocenteEscalafon(Carrera carrera, Docente docente, Date fechaNacimiento, String correoElectronico, String tipo, Set escalafons, Set cartillas) {
       this.carrera = carrera;
       this.docente = docente;
       this.fechaNacimiento = fechaNacimiento;
       this.correoElectronico = correoElectronico;
       this.tipo = tipo;
       this.escalafons = escalafons;
       this.cartillas = cartillas;
    }
   
    public String getCi() {
        return this.ci;
    }
    
    public void setCi(String ci) {
        this.ci = ci;
    }
    public Carrera getCarrera() {
        return this.carrera;
    }
    
    public void setCarrera(Carrera carrera) {
        this.carrera = carrera;
    }
    public Docente getDocente() {
        return this.docente;
    }
    
    public void setDocente(Docente docente) {
        this.docente = docente;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public String getCorreoElectronico() {
        return this.correoElectronico;
    }
    
    public void setCorreoElectronico(String correoElectronico) {
        this.correoElectronico = correoElectronico;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Set getEscalafons() {
        return this.escalafons;
    }
    
    public void setEscalafons(Set escalafons) {
        this.escalafons = escalafons;
    }
    public Set getCartillas() {
        return this.cartillas;
    }
    
    public void setCartillas(Set cartillas) {
        this.cartillas = cartillas;
    }




}


