package dea.modelo;
// Generated 16-may-2015 14:51:40 by Hibernate Tools 4.3.1



/**
 * Escalafon generated by hbm2java
 */
public class Escalafon  implements java.io.Serializable {


     private long idEscalafon;
     private Cartilla cartilla;
     private DocenteEscalafon docenteEscalafon;
     private double puntaje;
     private double puntajeAcumulado;
     private String categoria;
     private String gestion;
     private String obs;
     private long tipoRes;

    public Escalafon() {
    }

    public Escalafon(long idEscalafon, Cartilla cartilla, DocenteEscalafon docenteEscalafon, double puntaje, double puntajeAcumulado, String categoria, String gestion) {
       this.idEscalafon = idEscalafon;
       this.cartilla = cartilla;
       this.docenteEscalafon = docenteEscalafon;
       this.puntaje = puntaje;
       this.puntajeAcumulado = puntajeAcumulado;
       this.categoria = categoria;
       this.gestion = gestion;
    }
   
    public long getIdEscalafon() {
        return this.idEscalafon;
    }
    
    public void setIdEscalafon(long idEscalafon) {
        this.idEscalafon = idEscalafon;
    }
    public Cartilla getCartilla() {
        return this.cartilla;
    }
    
    public void setCartilla(Cartilla cartilla) {
        this.cartilla = cartilla;
    }
    public DocenteEscalafon getDocenteEscalafon() {
        return this.docenteEscalafon;
    }
    
    public void setDocenteEscalafon(DocenteEscalafon docenteEscalafon) {
        this.docenteEscalafon = docenteEscalafon;
    }
    public double getPuntaje() {
        return this.puntaje;
    }
    
    public void setPuntaje(double puntaje) {
        this.puntaje = puntaje;
    }
    public double getPuntajeAcumulado() {
        return this.puntajeAcumulado;
    }
    
    public void setPuntajeAcumulado(double puntajeAcumulado) {
        this.puntajeAcumulado = puntajeAcumulado;
    }
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }
    public String getGestion() {
        return this.gestion;
    }
    
    public void setGestion(String gestion) {
        this.gestion = gestion;
    }

    /**
     * @return the obs
     */
    public String getObs() {
        return obs;
    }

    /**
     * @param obs the obs to set
     */
    public void setObs(String obs) {
        this.obs = obs;
    }

    /**
     * @return the tipoRes
     */
    public long getTipoRes() {
        return tipoRes;
    }

    /**
     * @param tipoRes the tipoRes to set
     */
    public void setTipoRes(long tipoRes) {
        this.tipoRes = tipoRes;
    }




}


