package dea.modelo;
// Generated 16-may-2015 14:51:40 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Estudiante generated by hbm2java
 */
public class Estudiante  implements java.io.Serializable {


     private String ci;
     private Persona persona;
     private String estado;
     private Set estudianteRegistroMaterias = new HashSet(0);

    public Estudiante() {
    }

	
    public Estudiante(Persona persona) {
        this.persona = persona;
    }
    public Estudiante(Persona persona, String estado, Set estudianteRegistroMaterias) {
       this.persona = persona;
       this.estado = estado;
       this.estudianteRegistroMaterias = estudianteRegistroMaterias;
    }
   
    public String getCi() {
        return this.ci;
    }
    
    public void setCi(String ci) {
        this.ci = ci;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getEstudianteRegistroMaterias() {
        return this.estudianteRegistroMaterias;
    }
    
    public void setEstudianteRegistroMaterias(Set estudianteRegistroMaterias) {
        this.estudianteRegistroMaterias = estudianteRegistroMaterias;
    }




}


