package dea.modelo;
// Generated 16-may-2015 14:51:40 by Hibernate Tools 4.3.1



/**
 * EstudianteRegistroMateria generated by hbm2java
 */
public class EstudianteRegistroMateria  implements java.io.Serializable {


     private long idEstudianteRegistroMateria;
     private DocenteRegistroMateria docenteRegistroMateria;
     private Estudiante estudiante;
    
    public EstudianteRegistroMateria() {
    }

    public EstudianteRegistroMateria(DocenteRegistroMateria docenteRegistroMateria, Estudiante estudiante) {
       this.docenteRegistroMateria = docenteRegistroMateria;
       this.estudiante = estudiante;
       
    }
   
    public long getIdEstudianteRegistroMateria() {
        return this.idEstudianteRegistroMateria;
    }
    
    public void setIdEstudianteRegistroMateria(long idEstudianteRegistroMateria) {
        this.idEstudianteRegistroMateria = idEstudianteRegistroMateria;
    }
    public DocenteRegistroMateria getDocenteRegistroMateria() {
        return this.docenteRegistroMateria;
    }
    
    public void setDocenteRegistroMateria(DocenteRegistroMateria docenteRegistroMateria) {
        this.docenteRegistroMateria = docenteRegistroMateria;
    }
    public Estudiante getEstudiante() {
        return this.estudiante;
    }
    
    public void setEstudiante(Estudiante estudiante) {
        this.estudiante = estudiante;
    }
}


