package dea.modelo;
// Generated 16-may-2015 14:51:40 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Evaluacion generated by hbm2java
 */
public class Evaluacion  implements java.io.Serializable {


     private long idEvaluacion;
     private DocenteRegistroMateria docenteRegistroMateria;
     private Double nota;
     private Set contenidoCartillas = new HashSet(0);

    public Evaluacion() {
    }

	
    public Evaluacion(long idEvaluacion, DocenteRegistroMateria docenteRegistroMateria) {
        this.idEvaluacion = idEvaluacion;
        this.docenteRegistroMateria = docenteRegistroMateria;
    }
    public Evaluacion(long idEvaluacion, DocenteRegistroMateria docenteRegistroMateria, Double nota, Set contenidoCartillas) {
       this.idEvaluacion = idEvaluacion;
       this.docenteRegistroMateria = docenteRegistroMateria;
       this.nota = nota;
       this.contenidoCartillas = contenidoCartillas;
    }
   
    public long getIdEvaluacion() {
        return this.idEvaluacion;
    }
    
    public void setIdEvaluacion(long idEvaluacion) {
        this.idEvaluacion = idEvaluacion;
    }
    public DocenteRegistroMateria getDocenteRegistroMateria() {
        return this.docenteRegistroMateria;
    }
    
    public void setDocenteRegistroMateria(DocenteRegistroMateria docenteRegistroMateria) {
        this.docenteRegistroMateria = docenteRegistroMateria;
    }
    public Double getNota() {
        return this.nota;
    }
    
    public void setNota(Double nota) {
        this.nota = nota;
    }
    public Set getContenidoCartillas() {
        return this.contenidoCartillas;
    }
    
    public void setContenidoCartillas(Set contenidoCartillas) {
        this.contenidoCartillas = contenidoCartillas;
    }




}


