package dea.modelo;
// Generated 16-may-2015 14:51:40 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Facultad generated by hbm2java
 */
public class Facultad  implements java.io.Serializable {


     private long idFacultad;
     private Universidad universidad;
     private String siglaFacultad;
     private String nombre;
     private Set carreras = new HashSet(0);

    public Facultad() {
    }

	
    public Facultad(long idFacultad) {
        this.idFacultad = idFacultad;
    }
    public Facultad(long idFacultad, Universidad universidad, String siglaFacultad, String nombre, Set carreras) {
       this.idFacultad = idFacultad;
       this.universidad = universidad;
       this.siglaFacultad = siglaFacultad;
       this.nombre = nombre;
       this.carreras = carreras;
    }
   
    public long getIdFacultad() {
        return this.idFacultad;
    }
    
    public void setIdFacultad(long idFacultad) {
        this.idFacultad = idFacultad;
    }
    public Universidad getUniversidad() {
        return this.universidad;
    }
    
    public void setUniversidad(Universidad universidad) {
        this.universidad = universidad;
    }
    public String getSiglaFacultad() {
        return this.siglaFacultad;
    }
    
    public void setSiglaFacultad(String siglaFacultad) {
        this.siglaFacultad = siglaFacultad;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getCarreras() {
        return this.carreras;
    }
    
    public void setCarreras(Set carreras) {
        this.carreras = carreras;
    }




}


