package dea.modelo;
// Generated 16-may-2015 14:51:40 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Materia generated by hbm2java
 */
public class Materia  implements java.io.Serializable {


     private long idMateria;
     private Carrera carrera;
     private String siglaMateria;
     private String nombre;
     private Set docenteRegistroMaterias = new HashSet(0);
     private Set requiereMateriasForIdMateriaRequisito = new HashSet(0);
     private Set requiereMateriasForIdMateria = new HashSet(0);

    public Materia() {
    }

	
    public Materia(long idMateria, Carrera carrera, String siglaMateria) {
        this.idMateria = idMateria;
        this.carrera = carrera;
        this.siglaMateria = siglaMateria;
    }
    public Materia(long idMateria, Carrera carrera, String siglaMateria, String nombre, Set docenteRegistroMaterias, Set requiereMateriasForIdMateriaRequisito, Set requiereMateriasForIdMateria) {
       this.idMateria = idMateria;
       this.carrera = carrera;
       this.siglaMateria = siglaMateria;
       this.nombre = nombre;
       this.docenteRegistroMaterias = docenteRegistroMaterias;
       this.requiereMateriasForIdMateriaRequisito = requiereMateriasForIdMateriaRequisito;
       this.requiereMateriasForIdMateria = requiereMateriasForIdMateria;
    }
   
    public long getIdMateria() {
        return this.idMateria;
    }
    
    public void setIdMateria(long idMateria) {
        this.idMateria = idMateria;
    }
    public Carrera getCarrera() {
        return this.carrera;
    }
    
    public void setCarrera(Carrera carrera) {
        this.carrera = carrera;
    }
    public String getSiglaMateria() {
        return this.siglaMateria;
    }
    
    public void setSiglaMateria(String siglaMateria) {
        this.siglaMateria = siglaMateria;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getDocenteRegistroMaterias() {
        return this.docenteRegistroMaterias;
    }
    
    public void setDocenteRegistroMaterias(Set docenteRegistroMaterias) {
        this.docenteRegistroMaterias = docenteRegistroMaterias;
    }
    public Set getRequiereMateriasForIdMateriaRequisito() {
        return this.requiereMateriasForIdMateriaRequisito;
    }
    
    public void setRequiereMateriasForIdMateriaRequisito(Set requiereMateriasForIdMateriaRequisito) {
        this.requiereMateriasForIdMateriaRequisito = requiereMateriasForIdMateriaRequisito;
    }
    public Set getRequiereMateriasForIdMateria() {
        return this.requiereMateriasForIdMateria;
    }
    
    public void setRequiereMateriasForIdMateria(Set requiereMateriasForIdMateria) {
        this.requiereMateriasForIdMateria = requiereMateriasForIdMateria;
    }




}


