package dea.modelo;
// Generated 30-sep-2015 12:35:24 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Perfil generated by hbm2java
 */
public class Perfil  implements java.io.Serializable {
     private int idPerfil;
     private String perfil;
     private Set menus = new HashSet(0);
     private Set perfilPersonas = new HashSet(0);

    public Perfil() {
    }

	
    public Perfil(int idPerfil) {
        this.idPerfil = idPerfil;
    }
    public Perfil(int idPerfil, String perfil, Set menus, Set perfilPersonas) {
       this.idPerfil = idPerfil;
       this.perfil = perfil;
       this.menus = menus;
       this.perfilPersonas = perfilPersonas;
    }
   
    public int getIdPerfil() {
        return this.idPerfil;
    }
    
    public void setIdPerfil(int idPerfil) {
        this.idPerfil = idPerfil;
    }
    public String getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(String perfil) {
        this.perfil = perfil;
    }
    public Set getMenus() {
        return this.menus;
    }
    
    public void setMenus(Set menus) {
        this.menus = menus;
    }
    public Set getPerfilPersonas() {
        return this.perfilPersonas;
    }
    
    public void setPerfilPersonas(Set perfilPersonas) {
        this.perfilPersonas = perfilPersonas;
    }




}


