package dea.modelo;
// Generated 30-sep-2015 12:35:24 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private String ci;
     private String nombre;
     private String apellido;
     private String cuenta;
     private String contrasenia;
     private String estado;
     private String theme;
     private Set perfilPersonas = new HashSet(0);
     private Docente docente;
     private Estudiante estudiante;
     private AdministradorCoordinador administradorCoordinador;
     private AdministradorDirector administradorDirector;
    public Persona() {
    }

	
    public Persona(String ci) {
        this.ci = ci;
    }
    public Persona(String ci, String nombre, String apellido, String cuenta, String contrasenia, String estado, String theme, Set perfilPersonas, Docente docente, Estudiante estudiante, AdministradorCoordinador administradorCoordinador, AdministradorDirector administradorDirector) {
       this.ci = ci;
       this.nombre = nombre;
       this.apellido = apellido;
       this.cuenta = cuenta;
       this.contrasenia = contrasenia;
       this.estado = estado;
       this.theme = theme;
       this.perfilPersonas = perfilPersonas;
       this.docente = docente;
       this.estudiante = estudiante;
       this.administradorCoordinador = administradorCoordinador;
       this.administradorDirector = administradorDirector;
    }
   
    public String getCi() {
        return this.ci;
    }
    
    public void setCi(String ci) {
        this.ci = ci;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getCuenta() {
        return this.cuenta;
    }
    
    public void setCuenta(String cuenta) {
        this.cuenta = cuenta;
    }
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getTheme() {
        return this.theme;
    }
    
    public void setTheme(String theme) {
        this.theme = theme;
    }
    public Set getPerfilPersonas() {
        return this.perfilPersonas;
    }
    
    public void setPerfilPersonas(Set perfilPersonas) {
        this.perfilPersonas = perfilPersonas;
    }
    public Docente getDocente() {
        return this.docente;
    }
    
    public void setDocente(Docente docente) {
        this.docente = docente;
    }
    public Estudiante getEstudiante() {
        return this.estudiante;
    }
    
    public void setEstudiante(Estudiante estudiante) {
        this.estudiante = estudiante;
    }
    public AdministradorCoordinador getAdministradorCoordinador() {
        return this.administradorCoordinador;
    }
    
    public void setAdministradorCoordinador(AdministradorCoordinador administradorCoordinador) {
        this.administradorCoordinador = administradorCoordinador;
    }
    public AdministradorDirector getAdministradorDirector() {
        return this.administradorDirector;
    }
    
    public void setAdministradorDirector(AdministradorDirector administradorDirector) {
        this.administradorDirector = administradorDirector;
    }




}


