package dea.modelo;
// Generated 16-may-2015 14:51:40 by Hibernate Tools 4.3.1



/**
 * RequiereMateria generated by hbm2java
 */
public class RequiereMateria  implements java.io.Serializable {


     private RequiereMateriaId id;
     private Materia materiaByIdMateriaRequisito;
     private Materia materiaByIdMateria;

    public RequiereMateria() {
    }

    public RequiereMateria(RequiereMateriaId id, Materia materiaByIdMateriaRequisito, Materia materiaByIdMateria) {
       this.id = id;
       this.materiaByIdMateriaRequisito = materiaByIdMateriaRequisito;
       this.materiaByIdMateria = materiaByIdMateria;
    }
   
    public RequiereMateriaId getId() {
        return this.id;
    }
    
    public void setId(RequiereMateriaId id) {
        this.id = id;
    }
    public Materia getMateriaByIdMateriaRequisito() {
        return this.materiaByIdMateriaRequisito;
    }
    
    public void setMateriaByIdMateriaRequisito(Materia materiaByIdMateriaRequisito) {
        this.materiaByIdMateriaRequisito = materiaByIdMateriaRequisito;
    }
    public Materia getMateriaByIdMateria() {
        return this.materiaByIdMateria;
    }
    
    public void setMateriaByIdMateria(Materia materiaByIdMateria) {
        this.materiaByIdMateria = materiaByIdMateria;
    }




}


