package dea.modelo;
// Generated 16-may-2015 14:51:40 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Universidad generated by hbm2java
 */
public class Universidad  implements java.io.Serializable {


     private String siglaUniversidad;
     private String nombre;
     private Set facultads = new HashSet(0);

    public Universidad() {
    }

    public void addFacultad(Facultad f){
            facultads.add(f);
    }
    public Universidad(String siglaUniversidad, String nombre) {
        this.siglaUniversidad = siglaUniversidad;
        this.nombre = nombre;
    }
    public Universidad(String siglaUniversidad, String nombre, Set facultads) {
       this.siglaUniversidad = siglaUniversidad;
       this.nombre = nombre;
       this.facultads = facultads;
    }
   
    public String getSiglaUniversidad() {
        return this.siglaUniversidad;
    }
    
    public void setSiglaUniversidad(String siglaUniversidad) {
        this.siglaUniversidad = siglaUniversidad;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getFacultads() {
        return this.facultads;
    }
    
    public void setFacultads(Set facultads) {
        this.facultads = facultads;
    }




}


